<?php

/**
 * Shared Helper Functions
 *
 * This file contains small utility functions used by multiple other files.
 * Think of it as a "toolbox" — common tools that everyone in the plugin can borrow.
 *
 * Rules for this file:
 * - Functions here should be generic and reusable
 * - No function here should be specific to OAuth or user creation
 * - Keep functions small and focused on ONE task
 *
 * @package Google_Login_WP
 */

if (! defined('ABSPATH')) {
    exit;
}

// =============================================================================
// SETTINGS HELPERS
// =============================================================================

/**
 * Retrieves the plugin settings from the WordPress options table.
 *
 * WHY a wrapper function instead of calling get_option() directly?
 * 1. We can add defaults in ONE place — if we add a new setting later,
 *    we only update this function, not every place that reads settings.
 * 2. If the option doesn't exist yet (plugin just installed), we still
 *    get a usable array instead of FALSE.
 * 3. Every file can call glwp_get_settings() without knowing the option name.
 *
 * @return array Plugin settings with defaults for any missing keys.
 */
function glwp_get_settings()
{
    // get_option( 'option_name', $default ) returns $default if option doesn't exist.
    $saved = get_option('glwp_settings', array());

    // These are our "factory defaults" — what the plugin uses if a value
    // hasn't been saved yet.
    $defaults = array(
        'client_id'     => '',
        'client_secret' => '',
        'auto_register' => '1',
    );

    // array_merge: $saved values OVERRIDE $defaults.
    // So if 'client_id' is saved, it wins over the empty string default.
    // If a new setting was added to $defaults that isn't in $saved yet,
    // the default value is used automatically.
    return array_merge($defaults, $saved);
}

/**
 * Returns the Google OAuth Client ID from settings.
 *
 * @return string Client ID or empty string if not configured.
 */
function glwp_get_client_id()
{
    $settings = glwp_get_settings();
    return $settings['client_id'];
}

/**
 * Returns the Google OAuth Client Secret from settings.
 *
 * @return string Client Secret or empty string if not configured.
 */
function glwp_get_client_secret()
{
    $settings = glwp_get_settings();
    return $settings['client_secret'];
}

/**
 * Checks whether automatic account registration is enabled.
 *
 * @return bool True if new users can be auto-created, false otherwise.
 */
function glwp_is_auto_register_enabled()
{
    $settings = glwp_get_settings();
    return '1' === $settings['auto_register'];
}

// =============================================================================
// STATE / NONCE HELPERS (Anti-CSRF)
// =============================================================================

/**
 * Generates a cryptographically secure random state string and stores it.
 *
 * The "state" parameter is OAuth's equivalent of a nonce — it proves that
 * the callback response was triggered by THIS user on THIS site, not injected
 * by an attacker.
 *
 * Flow:
 * 1. We generate a random string
 * 2. We store it in a WordPress transient (temporary database entry)
 * 3. We send it to Google as part of the auth URL
 * 4. Google sends it back in the callback
 * 5. We check it matches what we stored → if yes, safe to continue
 *
 * WHY transients instead of PHP sessions?
 * WordPress doesn't start sessions by default, and starting sessions
 * on login pages can cause issues with caching plugins and hosting providers.
 * Transients use the WordPress database (or object cache), which is more
 * reliable in WordPress environments.
 *
 * @return string The generated state string (32 hex characters).
 */
function glwp_generate_oauth_state()
{
    // wp_generate_password with only hex-safe characters.
    // bin2hex( random_bytes(16) ) = 32 character hex string.
    // random_bytes() uses the operating system's cryptographically
    // secure random number generator — much stronger than rand() or mt_rand().
    $state = bin2hex(random_bytes(16));

    // Store in a transient that expires in 10 minutes.
    // The key includes the state value itself so we can look it up.
    // 'glwp_state_' prefix namespaces it to our plugin.
    set_transient('glwp_state_' . $state, '1', 10 * MINUTE_IN_SECONDS);
    // MINUTE_IN_SECONDS is a WordPress constant = 60.
    // 10 * 60 = 600 seconds = 10 minutes.
    // After 10 minutes the transient auto-deletes — expired states cannot be used.

    return $state;
}

/**
 * Validates that a state string was generated by us (not fabricated by an attacker).
 *
 * @param string $state The state string received in the callback URL.
 * @return bool True if valid and unused, false if invalid or expired.
 */
function glwp_validate_oauth_state($state)
{
    // Sanitize first — the state came from a URL parameter (user input).
    $state = sanitize_text_field($state);

    // Basic length check — our states are always 32 hex characters.
    if (empty($state) || strlen($state) !== 32) {
        return false;
    }

    // Check if this state exists in our transients.
    $stored = get_transient('glwp_state_' . $state);

    if (false === $stored) {
        // Transient doesn't exist: either expired, never existed, or already used.
        return false;
    }

    // DELETE the transient immediately after validation.
    // WHY? This makes the state "single use" — it cannot be replayed.
    // If an attacker somehow got a valid state and tried to use it twice,
    // the second attempt would fail because we deleted it after the first use.
    delete_transient('glwp_state_' . $state);

    return true;
}

// =============================================================================
// ERROR HANDLING HELPERS
// =============================================================================

/**
 * Redirects to the login page with an error message.
 *
 * We use this instead of wp_die() because:
 * - wp_die() shows a plain error page — bad UX for a login flow.
 * - Redirecting to login with an error message shows the user the login
 *   form again with a friendly message — much better UX.
 *
 * WordPress's login page automatically displays ?error=key messages
 * when we use the 'login_message' filter, but the simpler approach is
 * to add a custom query var and display it.
 *
 * @param string $error_code A short string identifying the error (e.g., 'state_mismatch').
 */
function glwp_redirect_with_error($error_code)
{
    // sanitize_key ensures the error code is safe to put in a URL.
    $error_code = sanitize_key($error_code);

    // Build the redirect URL: wp-login.php?glwp_error=error_code
    $url = add_query_arg(
        array('glwp_error' => $error_code),
        wp_login_url()
    );

    // wp_safe_redirect only allows redirecting to trusted domains.
    // This prevents "open redirect" attacks where an attacker tricks
    // your site into redirecting to a malicious external URL.
    wp_safe_redirect($url);
    exit; // ALWAYS call exit after wp_safe_redirect. Without it, PHP keeps running.
}

/**
 * Displays error messages on the login page from our OAuth flow.
 *
 * Hooked to 'login_messages' — this filter lets plugins add messages
 * above the login form.
 *
 * @param string $message Existing login messages (from WordPress itself).
 * @return string Updated messages HTML.
 */
function glwp_display_login_error($message)
{
    // phpcs:ignore WordPress.Security.NonceVerification.Recommended
    if (! isset($_GET['glwp_error'])) {
        return $message;
    }

    // sanitize_key: only allows lowercase letters, numbers, hyphens, underscores.
    $error_code = sanitize_key($_GET['glwp_error']);

    // Map error codes to human-readable messages.
    // WHY error codes instead of passing the message in the URL?
    // 1. Internationalization: we translate here, not in the URL.
    // 2. Security: user input in URLs could contain HTML/scripts. Error codes are safe.
    // 3. Cleaner URLs.
    $errors = array(
        'state_mismatch'    => __('Security check failed. Please try logging in again.', 'google-login-wp'),
        'no_code'           => __('Google did not return an authorization code. Please try again.', 'google-login-wp'),
        'token_failed'      => __('Could not connect to Google. Please try again later.', 'google-login-wp'),
        'userinfo_failed'   => __('Could not retrieve your Google profile. Please try again.', 'google-login-wp'),
        'no_email'          => __('Your Google account does not have a verified email address.', 'google-login-wp'),
        'registration_off'  => __('Account registration is disabled. Contact the site administrator.', 'google-login-wp'),
        'login_failed'      => __('Login failed. Please try again or contact the administrator.', 'google-login-wp'),
        'not_configured'    => __('Google Login is not configured. Please contact the site administrator.', 'google-login-wp'),
    );

    if (! array_key_exists($error_code, $errors)) {
        // Unknown error code — show a generic message.
        $error_text = __('An unknown error occurred. Please try again.', 'google-login-wp');
    } else {
        $error_text = $errors[$error_code];
    }

    // Build the message HTML.
    // WordPress login uses <div class="message error"> for error notices.
    // esc_html() prevents any HTML in the error text from rendering as HTML.
    $message .= '<div class="message error" id="glwp-login-error">';
    $message .= esc_html($error_text);
    $message .= '</div>';

    return $message;
}
add_filter('login_messages', 'glwp_display_login_error');

// =============================================================================
// SVG / UI HELPERS
// =============================================================================

/**
 * Returns the Google "G" logo as an inline SVG string.
 *
 * WHY a function? Keeps the main template code clean.
 * WHY inline SVG? No extra HTTP request, no CORS issues, scales perfectly.
 *
 * The SVG is hardcoded (not from user input), so it's safe to output
 * without escaping — but we'd normally use wp_kses() for any SVG that
 * could contain dynamic data.
 *
 * @return string SVG markup.
 */
function glwp_get_google_icon_svg()
{
    // This is Google's official "G" logo in SVG format.
    // Source: Google Brand Guidelines (publicly available).
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="20" height="20" aria-hidden="true">
		<path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"/>
		<path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"/>
		<path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"/>
		<path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"/>
		<path fill="none" d="M0 0h48v48H0z"/>
	</svg>';
}

// =============================================================================
// LOGGING HELPER (Development Aid)
// =============================================================================

/**
 * Logs a message to the WordPress debug log.
 *
 * Only logs when WP_DEBUG and WP_DEBUG_LOG are both enabled in wp-config.php.
 * In production, these should be FALSE so nothing is logged.
 *
 * Usage:
 *   glwp_log( 'Token exchange failed', $response_data );
 *   glwp_log( 'User created with ID: ' . $user_id );
 *
 * To see logs: check wp-content/debug.log
 *
 * @param string $message Description of what's happening.
 * @param mixed  $data    Optional extra data to dump (array, object, etc.).
 */
function glwp_log($message, $data = null)
{
    if (! defined('WP_DEBUG') || ! WP_DEBUG) {
        return; // Don't log in production.
    }
    if (! defined('WP_DEBUG_LOG') || ! WP_DEBUG_LOG) {
        return; // Don't log if logging is disabled.
    }

    $prefix = '[Google Login WP] ';
    if (null !== $data) {
        // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
        error_log($prefix . $message . ' | Data: ' . print_r($data, true));
    } else {
        // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
        error_log($prefix . $message);
    }
}
